os:
  - linux

language:
  - cpp

compiler:
  - gcc
  - clang

env:
  global:
    - PEAK_DRIVER_VER=8.5.1

before_install:
  - sudo apt-get -qq update # -qq No output except for errors
  - '[[ "$TRAVIS_EVENT_TYPE" = cron ]] && export ROBOTOLOGY_CHECKOUT=devel || export ROBOTOLOGY_CHECKOUT=master'

  #-- Register SSH deploy key for AMOR API private repository
  #-- https://gist.github.com/lukewpatterson/4242707#gistcomment-2382443
  #-- http://anil.recoil.org/2013/10/06/travis-secure-ssh-integration.html
  - mkdir -p ~/.ssh
  - echo $DEPLOY_KEY_AMOR_API | base64 --decode | openssl aes-256-cbc -K $encrypted_7b486c11a122_key -iv $encrypted_7b486c11a122_iv -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo "Host *" >> ~/.ssh/config
  - echo "    StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "    CheckHostIP no" >> ~/.ssh/config
  - echo "    PasswordAuthentication no" >> ~/.ssh/config
  - echo "    UserKnownHostsFile=/dev/null" >> ~/.ssh/config

install:
  #-- Install 3rd-party dependencies
  - sudo apt-get install libboost-thread-dev libeigen3-dev libspnav-dev libxwiimote-dev libusb-1.0-0-dev libgtest-dev
  #-- Install color-debug
  - git clone https://github.com/roboticslab-uc3m/color-debug
  - cd color-debug && mkdir build && cd build
  - cmake ..
  - sudo make install
  - cd ../..
  #-- Install ycm
  - git clone --branch="$ROBOTOLOGY_CHECKOUT" https://github.com/robotology/ycm
  - cd ycm && mkdir build && cd build
  - cmake ..
  - make -j$(nproc)
  - sudo make install
  - cd ../..
  #-- Install yarp
  - git clone --branch="$ROBOTOLOGY_CHECKOUT" https://github.com/robotology/yarp
  - cd yarp && mkdir build && cd build
  - cmake .. -DSKIP_ACE=ON
  - make -j$(nproc)
  - sudo make install
  - cd ../..
  #-- Install libphidget21
  - cd extern/phidget
  - tar xzf libphidget_2.1.8.20151217.tar.gz
  - cd libphidget-2.1.8.20151217
  - ./configure --enable-jni=no
  - make -j$(nproc)
  - sudo make install
  - cd ../../..
  #-- Download and install Peak CAN driver
  - wget -O- https://www.peak-system.com/fileadmin/media/linux/files/peak-linux-driver-$PEAK_DRIVER_VER.tar.gz | tar xz
  - cd peak-linux-driver-$PEAK_DRIVER_VER
  - make -C lib
  - sudo make -C lib install
  - sudo cp -f driver/pcan.h driver/pcanfd.h /usr/include # hardcoded install path
  - cd ..
  #-- Install AMOR API
  - git clone git@github.com:roboticslab-uc3m/amor-api
  - cd amor-api && mkdir build && cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
  # see http://gronlier.fr/blog/2015/01/adding-code-coverage-to-your-c-project/
  - if [ "$CXX" = "g++" ]; then wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz; fi
  - if [ "$CXX" = "g++" ]; then tar xf lcov_1.11.orig.tar.gz; fi
  - if [ "$CXX" = "g++" ]; then sudo make -C lcov-1.11/ install; fi
  - if [ "$CXX" = "g++" ]; then gem install coveralls-lcov; fi

before_script:
  - mkdir -p build && cd build
  - cmake .. -DENABLE_coverage=ON

script:
  - make
  - sudo make install

after_success:
  #  - cd ${TRAVIS_BUILD_DIR}
  # capture coverage info
  - if [ "$CXX" = "g++" ]; then lcov --directory . --capture --output-file coverage.info; fi
  # filter out system and test code
  - if [ "$CXX" = "g++" ]; then lcov --remove coverage.info  '/usr/*' 'test/*' --output-file coverage.info; fi
  # debug before upload
  - if [ "$CXX" = "g++" ]; then lcov --list coverage.info; fi
  # uploads to coveralls
  #- if [ "$CXX" = "g++" ]; then coveralls-lcov --source-encoding=ISO-8859-1 --repo-token InWqFy6VWMrEUzr2Rn8XV0cGqv3wXWo2d coverage.info; fi
  - if [ "$CXX" = "g++" ]; then coveralls-lcov --source-encoding=ISO-8859-1 coverage.info; fi

  - sudo make uninstall
